### ISSUE TITLE
The top N populated countries in a continent where N is provided by the user

### ISSUE THREAD

**Issue by JasonS20** [vladkoisnych/sem_group_project_25#18]

**Comment by JasonS20** [comment]
As an organisation, we want to use a computer so that we can see a list of a given amount of countries in a continent in population order from largest to smallest.

**Comment by JO5-YSF** [comment]
solution for report 18 : 

String strSelect =
                    "SELECT Code, Name, Population " +
                    "FROM country " +
                    "WHERE Continent = '" + continent + "' " +
                    "ORDER BY Population DESC " +
                    "LIMIT " + N;
